FROM eclipse-temurin:11-jre-jammy

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN curl -fL -o /otp.jar \
  https://repo1.maven.org/maven2/org/opentripplanner/otp/1.5.0/otp-1.5.0-shaded.jar

WORKDIR /var/opentripplanner

ENTRYPOINT ["java", "-Xmx12G", "-jar", "/otp.jar"]
